version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      #- $HOME/docker_data/mongo-volume:/data/db
      - $PWD/mongo-config/mongod.conf:/etc/mongod.conf
      - $PWD/mongo-config/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - $HOME/docker_data/mongo/data:/data/
      #- $HOME/docker_data/mongo/log:/var/log/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "Abc#1234"
      MONGO_INITDB_DATABASE: "admin"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "Abc#1234"
